### PR TITLE
New changes

### PR DESCRIPTION
**Pull request by Jossy6**
I edited the readme file

### CODE REVIEW

**Review by wintan1418 — CHANGES_REQUESTED** [review]
where is the code? where are the files? then the form should be centered..margin top .justify and allign to center. welldone... please fix this things and ask for another review when done.

**Comment by Jossy6** [comment]
Screenshot (83)

**Review by wintan1418 — APPROVED** [review]
close, still missing some things. would comment later.

**Comment by Jossy6** [comment]
Okay sir

**Pull request merged**
